export const queryKey = {
  RES_ROOM_CLASS_BED_TYPE_LIST: 'RES_ROOM_CLASS_BED_TYPE_LIST',
  RES_ROOM_CLASS_LIST: 'RES_ROOM_CLASS_LIST',
  RES_BED_TYPE_LIST: 'RES_BED_TYPE_LIST',
  ROOM_CLASS_BED_TYPE_DETAIL: 'ROOM_CLASS_BED_TYPE_DETAIL',
}
